# Tensor Practice: Slicing, Multiplication, Broadcasting & Ops

Hands-on drills for the core PyTorch tensor moves used throughout this repo
(see `broadcasting_tutorial.ipynb` and `makemore_MLP.ipynb`).

**How to use this notebook:**
1. Run the setup cell for an exercise (creates the input tensors).
2. Fill in `result = ...` in the same cell, replacing the `None`.
3. Run the **check cell** right after it. It tells you whether your `result`
   has the right **shape**, and — only if the shape is right — whether the
   **values** are correct. It never prints or reveals the correct answer, so
   you can retry without being spoiled.
4. If you get stuck, the **Solutions** section at the very bottom has the
   answer for every exercise — but no peeking until you've had a real go!

Run the next cell once before starting.

In [1]:
import torch
import hashlib

def _tensor_hash(t):
    t = torch.as_tensor(t).detach().cpu().contiguous().double()
    rounded = torch.round(t * 1e4) / 1e4
    payload = rounded.numpy().tobytes() + str(tuple(rounded.shape)).encode()
    return hashlib.sha256(payload).hexdigest()[:16]

def check(name, result, expected_shape, expected_hash):
    """Verify `result` against a hidden expected shape/hash without revealing it."""
    if result is None:
        print(f"[{name}] -> fill in `result` above, then re-run this cell.")
        return
    result = torch.as_tensor(result)
    got_shape = tuple(result.shape)
    if got_shape != expected_shape:
        print(f"[{name}] shape mismatch: got {got_shape}, expected {expected_shape}")
        return
    if _tensor_hash(result) == expected_hash:
        print(f"[{name}] correct!")
    else:
        print(f"[{name}] shape is right, but the values are off. Keep trying.")


## 1. Slicing — submatrix

`A` is a 6x6 tensor of consecutive floats.

Extract the 3x3 submatrix covering **rows 1-3** and **columns 2-4** (inclusive) into `result`.

In [19]:
A = torch.arange(36).float().reshape(6, 6)
print(A)

A = A[1:4,2:5]
print(A)

result = A  # TODO: replace with your answer


tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.],
        [12., 13., 14., 15., 16., 17.],
        [18., 19., 20., 21., 22., 23.],
        [24., 25., 26., 27., 28., 29.],
        [30., 31., 32., 33., 34., 35.]])
tensor([[ 8.,  9., 10.],
        [14., 15., 16.],
        [20., 21., 22.]])


In [20]:
check("e1", result, (3, 3), "0434997a8482350a")

[e1] correct!


## 2. Slicing — stride + flip

`B` is a 4x4 tensor.

Take every other row of `B` starting from row 0 (rows 0 and 2), then **reverse the row order** of that selection. Store the final 2x4 tensor in `result`.

(Note: torch doesn't support negative-step slicing like numpy — use `.flip(dim)` for the reversal.)

In [47]:
B = torch.arange(1, 17).float().reshape(4, 4)
print(B)

B = B[::2,:]
print(B)

B = torch.flip(B,[0])
print(B)

result = B  # TODO: replace with your answer


tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 9., 10., 11., 12.]])
tensor([[ 9., 10., 11., 12.],
        [ 1.,  2.,  3.,  4.]])


In [48]:
check("e2", result, (2, 4), "654b4b68dcce3de4")

[e2] correct!


## 3. Fancy indexing — paired row/col gather

`C` is a 5x4 tensor. `row_idx` and `col_idx` are 1D index tensors of length 5.

This is the same trick used in `makemore_MLP.ipynb` to pick out the predicted probability of the correct next character: `prob[torch.arange(32), Y]`.

Using `row_idx` and `col_idx` as **paired** indices, gather one value per row of `C` into a 1D tensor `result` of length 5, where `result[i] == C[row_idx[i], col_idx[i]]`.

In [52]:
torch.manual_seed(3)
C = torch.rand(5, 4)
row_idx = torch.arange(5)
col_idx = torch.tensor([0, 3, 1, 2, 0])
print(C)

result = []
for i in range(C.shape[0]):
    result.append(C[row_idx[i],col_idx[i]])

result = result  # TODO: replace with your answer


tensor([[0.0043, 0.1056, 0.2858, 0.0270],
        [0.4716, 0.0601, 0.7719, 0.7437],
        [0.5944, 0.8879, 0.4510, 0.7995],
        [0.1498, 0.4015, 0.0542, 0.4594],
        [0.1756, 0.9492, 0.8473, 0.8749]])


In [53]:
check("e3", result, (5,), "e00becdc8450faf4")

[e3] correct!


## 4. Boolean mask indexing

`D` is a 5x5 tensor of integers in [-10, 10].

Build `result`, a 1D tensor containing only the **positive** elements of `D` (strictly greater than 0), in the order a boolean mask index returns them.

In [ ]:
torch.manual_seed(4)
D = torch.randint(-10, 11, (5, 5)).float()
print(D)

result = None  # TODO: replace with your answer


In [ ]:
check("e4", result, (10,), "c2da293401fbd697")

## 5. Elementwise (Hadamard) product

`E1` and `E2` are both 3x4 tensors.

Compute their **elementwise** product (not matrix multiplication) into `result`.

In [ ]:
torch.manual_seed(5)
E1 = torch.rand(3, 4)
E2 = torch.rand(3, 4)
print(E1)
print(E2)

result = None  # TODO: replace with your answer


In [ ]:
check("e5", result, (3, 4), "fec996e588b2dc05")

## 6. Matrix multiplication

`F1` has shape (4, 3), `F2` has shape (3, 5).

Compute the proper matrix product of `F1` and `F2` into `result` (shape (4, 5)).

In [ ]:
torch.manual_seed(6)
F1 = torch.rand(4, 3)
F2 = torch.rand(3, 5)
print(F1)
print(F2)

result = None  # TODO: replace with your answer


In [ ]:
check("e6", result, (4, 5), "b8fa4905c70285d9")

## 7. Batched matrix multiplication

`G1` has shape (2, 3, 4) and `G2` has shape (2, 4, 5) — two batches of matrices, batch dimension first.

Compute `result` of shape (2, 3, 5) such that `result[i] == G1[i] @ G2[i]` for each batch `i`, without writing a Python loop.

In [ ]:
torch.manual_seed(7)
G1 = torch.rand(2, 3, 4)
G2 = torch.rand(2, 4, 5)
print(G1.shape, G2.shape)

result = None  # TODO: replace with your answer


In [ ]:
check("e7", result, (2, 3, 5), "2893b51a61f03a8f")

## 8. Broadcasting — add a row vector

`H` has shape (4, 5). `row` has shape (5,).

Add `row` to **every row** of `H` via broadcasting (no loops) into `result`.

In [ ]:
torch.manual_seed(8)
H = torch.rand(4, 5)
row = torch.rand(5)
print(H)
print(row)

result = None  # TODO: replace with your answer


In [ ]:
check("e8", result, (4, 5), "0dfefa4476a9ddef")

## 9. Broadcasting — normalize rows

`K` has shape (4, 6). This is the same pattern as the softmax step `prob = counts / counts.sum(1, keepdims=True)` in `makemore_MLP.ipynb`.

Normalize `K` so that **each row sums to 1**, by dividing every row by its own sum, using broadcasting with `keepdim=True`. Store in `result`.

In [ ]:
torch.manual_seed(9)
K = torch.rand(4, 6)
print(K)

result = None  # TODO: replace with your answer


In [ ]:
check("e9", result, (4, 6), "8fc981e5f8afc367")

## 10. Broadcasting — outer product

`u` has shape (4,), `v` has shape (3,).

Using broadcasting (not `torch.outer`), compute `result` of shape (4, 3) where `result[i, j] == u[i] * v[j]`.

Hint: use `None` / `.unsqueeze()` to insert a size-1 dimension.

In [ ]:
torch.manual_seed(10)
u = torch.rand(4)
v = torch.rand(3)
print(u)
print(v)

result = None  # TODO: replace with your answer


In [ ]:
check("e10", result, (4, 3), "bf654ef34630e184")

## 11. Reshape + transpose

`L` is a 1D tensor of length 24.

Reshape `L` into shape (4, 6), then transpose it to shape (6, 4). Store the final tensor in `result`.

In [ ]:
L = torch.arange(24).float()
print(L)

result = None  # TODO: replace with your answer


In [ ]:
check("e11", result, (6, 4), "bf4fcf261cd01d92")

## 12. Reduction — argmax along a dimension

`M` has shape (5, 7).

For **each row**, find the column index of the maximum value. Store the resulting 1D tensor of length 5 in `result`.

In [ ]:
torch.manual_seed(12)
M = torch.rand(5, 7)
print(M)

result = None  # TODO: replace with your answer


In [ ]:
check("e12", result, (5,), "c37225c2c2f05a0a")

## Bonus A. Pairwise squared distances via broadcasting

`P` holds 4 points in 2D (shape (4, 2)), `Q` holds 3 points in 2D (shape (3, 2)).

Using broadcasting only (no Python loops), compute `result` of shape (4, 3) where `result[i, j]` is the **squared Euclidean distance** between `P[i]` and `Q[j]`.

Hint: insert a middle dimension on one tensor and a leading dimension on the other so they broadcast to shape (4, 3, 2), then square and sum over the last axis.

In [ ]:
torch.manual_seed(20)
P = torch.rand(4, 2)
Q = torch.rand(3, 2)
print(P)
print(Q)

result = None  # TODO: replace with your answer


In [ ]:
check("e13", result, (4, 3), "7f7b5761a262b095")

## Bonus B. One-hot encoding via broadcasting

`labels` is a 1D tensor of 5 class indices, each in [0, 6).

Using a broadcasted **comparison** (no loops, no `F.one_hot`), build `result`, a (5, 6) float tensor that is the one-hot encoding of `labels`.

In [ ]:
torch.manual_seed(21)
labels = torch.randint(0, 6, (5,))
print(labels)

result = None  # TODO: replace with your answer


In [ ]:
check("e14", result, (5, 6), "02d44d16e405a573")

---
## Solutions (spoilers below!)

Only look at a solution after you've actually attempted the exercise above —
compare it to your own approach once the check cell says you're correct
(or once you're truly stuck).

**1. Slicing — submatrix**

In [ ]:
A = torch.arange(36).float().reshape(6, 6)
print(A)

result = A[1:4, 2:5]
print(result)

**2. Slicing — stride + flip**

In [ ]:
B = torch.arange(1, 17).float().reshape(4, 4)
print(B)

result = B[::2].flip(0)
print(result)

**3. Fancy indexing — paired row/col gather**

In [ ]:
torch.manual_seed(3)
C = torch.rand(5, 4)
row_idx = torch.arange(5)
col_idx = torch.tensor([0, 3, 1, 2, 0])
print(C)

result = C[row_idx, col_idx]
print(result)

**4. Boolean mask indexing**

In [ ]:
torch.manual_seed(4)
D = torch.randint(-10, 11, (5, 5)).float()
print(D)

result = D[D > 0]
print(result)

**5. Elementwise (Hadamard) product**

In [ ]:
torch.manual_seed(5)
E1 = torch.rand(3, 4)
E2 = torch.rand(3, 4)
print(E1)
print(E2)

result = E1 * E2
print(result)

**6. Matrix multiplication**

In [ ]:
torch.manual_seed(6)
F1 = torch.rand(4, 3)
F2 = torch.rand(3, 5)
print(F1)
print(F2)

result = F1 @ F2
print(result)

**7. Batched matrix multiplication**

In [ ]:
torch.manual_seed(7)
G1 = torch.rand(2, 3, 4)
G2 = torch.rand(2, 4, 5)
print(G1.shape, G2.shape)

result = G1 @ G2
print(result)

**8. Broadcasting — add a row vector**

In [ ]:
torch.manual_seed(8)
H = torch.rand(4, 5)
row = torch.rand(5)
print(H)
print(row)

result = H + row
print(result)

**9. Broadcasting — normalize rows**

In [ ]:
torch.manual_seed(9)
K = torch.rand(4, 6)
print(K)

result = K / K.sum(dim=1, keepdim=True)
print(result)

**10. Broadcasting — outer product**

In [ ]:
torch.manual_seed(10)
u = torch.rand(4)
v = torch.rand(3)
print(u)
print(v)

result = u[:, None] * v[None, :]
print(result)

**11. Reshape + transpose**

In [ ]:
L = torch.arange(24).float()
print(L)

result = L.reshape(4, 6).T
print(result)

**12. Reduction — argmax along a dimension**

In [ ]:
torch.manual_seed(12)
M = torch.rand(5, 7)
print(M)

result = M.argmax(dim=1)
print(result)

**Bonus A. Pairwise squared distances via broadcasting**

In [ ]:
torch.manual_seed(20)
P = torch.rand(4, 2)
Q = torch.rand(3, 2)
print(P)
print(Q)

diff = P[:, None, :] - Q[None, :, :]
result = (diff ** 2).sum(-1)
print(result)

**Bonus B. One-hot encoding via broadcasting**

In [ ]:
torch.manual_seed(21)
labels = torch.randint(0, 6, (5,))
print(labels)

classes = torch.arange(6)
result = (labels[:, None] == classes[None, :]).float()
print(result)